name: malli
description: MALLI medical imaging scaffold for low-cost Android devices
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+1
  path_provider: ^2.0.15
  sqflite: ^2.2.8
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
